name: Node & .Net CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install node_modules
      run: npm i
      working-directory: SmokeyWay/SmokeyWay/ClientApp/
    - name: Run ESLint
      run: npm run lint
      working-directory: SmokeyWay/SmokeyWay/ClientApp/
    - name: Build
      run: npm run build --if-present
      working-directory: SmokeyWay/SmokeyWay/ClientApp/
    #- run: npm test
    - name: .NET Core
      uses: actions/checkout@v2
    - name: Setup .NET Core      
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301      
    - name: Install dependencies
      run: dotnet restore
      working-directory: SmokeyWay/SmokeyWay
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: SmokeyWay/SmokeyWay
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: SmokeyWay/SmokeyWay
    - name: dotnet publish
      run: dotnet publish -c Release -o myapp 
    - name: FTP Deployment
      # You may pin to the exact commit or the version.
      # uses: airvzxf/ftp-deployment-action@c4699e3438a88a8a9d00c1311b98d2ca94f32754
      uses: airvzxf/ftp-deployment-action@v1.0-alpha.2
      with:
        # FTP Server
        server: ${{secrets.FTP_ADDRESS}}
        # FTP User
        user: ${{secrets.FTP_USERNAME}}
        # FTP Password
        password: ${{secrets.FTP_PASSWORD}}
        # Delete all the files inside of the remote directory
        delete: true
        # Local directory
        local_dir: ./myapp
        # Remote directory
        remote_dir: site1
