# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install node_modules
      run: npm install
      working-directory: SmokeyWay/SmokeyWay/ClientApp/
    - name: Configure ESLint
      run: npm install eslint
    - name: Run ESLint
      run: npm install
    - name: Build
      run: npm run build --if-present
      working-directory: SmokeyWay/SmokeyWay/ClientApp/
    #- run: npm test
