# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node & .Net CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install node_modules
      run: npm install
      working-directory: SmokeyWay/SmokeyWay/ClientApp/
    - name: Build
      run: npm run build --if-present
      working-directory: SmokeyWay/SmokeyWay/ClientApp/
    - name: Configure ESLint
      run: npm install eslint
    - name: Run ESLint
      run: npm install
    #- run: npm test
    - name: .NET Core
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
      
    - name: Install dependencies
      run: dotnet restore
      working-directory: SmokeyWay/SmokeyWay
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: SmokeyWay/SmokeyWay
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: SmokeyWay/SmokeyWay


